### ISSUE TITLE
Login Form

### ISSUE THREAD

**Issue by divyeshJoshiG** [negi-rohan/video-tutorial#1]
Forgot Password:

Phase 1 : Should be able to set password through email 

Sample code to be referred to:
https://www.npmjs.com/package/password-reset-nodemailer
http://sahatyalkabov.com/how-to-implement-password-reset-in-nodejs/

**Comment by negi-rohan** [comment]
Forget password implemented.

**Comment by divyeshJoshiG** [comment]
It should be "Forgot Password"
